apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vrcbdfm1a-nodejs 
  janus-idp.io/tekton: vrcbdfm1a-nodejs
  backstage.io/kubernetes-id: vrcbdfm1a-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vrcbdfm1a-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml